# Generated by Django 3.2.5 on 2022-02-28 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intro', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='intro',
            name='pic',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
